---
- name: Allow setting vip
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf
  notify: Restart HAProxy and Keepalived

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_config_file }}"
    owner: haproxy
    group: haproxy
    mode: '0644'
  notify: Restart HAProxy and Keepalived

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_config_file }}"
    owner: keepalived
    group: keepalived
    mode: '0644'
  notify: Restart HAProxy and Keepalived