---
- name: Allow setting vip
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf
  notify: Restart HAProxy and Keepalived

- name: Create directory for HAProxy UNIX socket
  file:
    path: /run/haproxy # const value, don't change it!
    state: directory
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: '0755'
  notify: Restart HAProxy and Keepalived

- name: Create HAProxy error pages directory
  file:
    path: "{{ haproxy_errors_directory }}"
    state: directory
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: '0755'
  notify: Restart HAProxy and Keepalived

- name: Copy HAProxy error pages
  copy:
    src: "errors/{{ item }}"
    dest: "/etc/haproxy/errors/{{ item }}"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: '0644'
  with_items:
    - 400.http
    - 403.http
    - 408.http
    - 500.http
    - 502.http
    - 503.http
    - 504.http
  notify: Restart HAProxy and Keepalived

- name: Create HAProxy log files
  file:
    path: "{{ item }}"
    state: touch
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: '0644'
  loop: # const values, don't change them!
    - /var/log/haproxy.log
    - /var/log/haproxy-status.log
  notify:
    - Restart HAProxy and Keepalived
    - Restart rsyslog

- name: Configure rsyslog for HAProxy
  template:
    src: haproxy.conf.j2
    dest: /etc/rsyslog.d/haproxy.conf # const value, don't change it!
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: '0644'
  notify:
    - Restart HAProxy and Keepalived
    - Restart rsyslog

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_config_file }}"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: '0644'
  notify: Restart HAProxy and Keepalived

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_config_file }}"
    owner: "{{ keepalived_user }}"
    group: "{{ keepalived_group }}"
    mode: '0644'
  notify: Restart HAProxy and Keepalived