---
- name: Allow setting vip
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf
  notify: Restart HAProxy and Keepalived

- name: Copy HAProxy error pages
  copy:
    src: "errors/{{ item }}"
    dest: "/etc/haproxy/errors/{{ item }}"
    owner: haproxy
    group: haproxy
    mode: '0644'
  with_items:
    - 400.http
    - 403.http
    - 408.http
    - 500.http
    - 502.http
    - 503.http
    - 504.http
  notify: Restart HAProxy and Keepalived

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_config_file }}"
    owner: haproxy
    group: haproxy
    mode: '0644'
  notify: Restart HAProxy and Keepalived

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_config_file }}"
    owner: keepalived
    group: keepalived
    mode: '0644'
  notify: Restart HAProxy and Keepalived