---
- name: Restart HAProxy
  service:
    name: haproxy
    state: restarted
  listen: Restart HAProxy and Keepalived

- name: Restart Keepalived
  service:
    name: keepalived
    state: restarted
  listen: Restart HAProxy and Keepalived